import Head from 'next/head';
import CheckoutPage from '../components/CheckoutPage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rudra Developers - Mango Sale</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <CheckoutPage />
    </div>
  )
}
