import Head from "next/head";
import { useState } from "react";
import { CartContext } from "../context/cart";
import { ActionContext } from "../context/action";
import { InventoryContext } from "../context/inventory";
import { db } from "../firebase";
import { collection, getDocs } from "firebase/firestore";
import MainSection from "../components/MainSection";

export default function Home({ inventoryArray }) {
	const [cart, setCart] = useState({});
	const cartSetter = newCart => {
		setCart(newCart);
	};

	return (
		<InventoryContext.Provider value={{ inventory: inventoryArray }}>
			<CartContext.Provider value={{ cart, setCart: cartSetter }}>
				<Head>
					<title>Rudra Developers - Mango Sale</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
				</Head>
				<MainSection />
			</CartContext.Provider>
		</InventoryContext.Provider>
	);
}

export async function getServerSideProps() {
	let inventoryArray = {};
	const inventoryReference = collection(db, "inventory");
	const inventorySnapshot = await getDocs(inventoryReference);
	const arrayOfMangoes = inventorySnapshot.docs;
	arrayOfMangoes.forEach(mango => {
		const mangoData = mango.data();
		const mangoName = mangoData.name;
		inventoryArray[mangoName] = { ...mangoData, quantity: 0 };
	});
	return {
		props: {
			inventoryArray,
		},
	};
}
