import Head from "next/head";
import MainSection from "../components/MainSection";
import Cart from "../components/Cart";
import CheckoutSection from "../components/CheckoutSection";

import { useContext } from "react";
import { ViewContext } from "../context/view";
import { InventoryContext } from "../context/inventory";

import { db } from "../firebase";
import { collection, getDocs } from "firebase/firestore";

export default function Home({ inventoryArray }) {
	const { view } = useContext(ViewContext);
	const Component = () => {
		if (view === "home") return <MainSection />;
		if (view === "cart") return <Cart />;
		if (view === "checkout") return <CheckoutSection />;
	};

	return (
		<InventoryContext.Provider value={{ inventory: inventoryArray }}>
			<Head>
				<title>Rudra Developers - Mango Sale</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<Component />
		</InventoryContext.Provider>
	);
}

export async function getServerSideProps() {
	let inventoryArray = {};
	const inventoryReference = collection(db, "inventory");
	const inventorySnapshot = await getDocs(inventoryReference);
	const arrayOfMangoes = inventorySnapshot.docs;
	arrayOfMangoes.forEach(mango => {
		const mangoData = mango.data();
		const mangoName = mangoData.name;
		inventoryArray[mangoName] = { ...mangoData, quantity: 0 };
	});
	return {
		props: {
			inventoryArray,
		},
	};
}
