import Head from 'next/head';
import HomePage from '../components/HomePage';
import Script from 'next/script';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rudra Developers - Mango Sale</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Script>
        <script src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_API_KEY}&libraries=places&callback=initAutoComplete`} async defer></script>
      </Script>
      <HomePage />
    </div>
  )
}
